name: Build & Test (Windows, MSVC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Configure CMake
      run: cmake -B ./build

    - name: Build
      run: cmake --build ./build --config Release

#    - name: Test
#      run: ./build/Release/caramel_test.exe
